# Generated by Django 4.0.3 on 2022-03-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='ratio',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
